
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 11 22:59:23 CET 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int t_etat = 27;
  public static final int t_DECLA_APP_OUV = 4;
  public static final int FSI = 19;
  public static final int t_comparateurs = 41;
  public static final int t_message = 28;
  public static final int EGAL = 37;
  public static final int SI = 16;
  public static final int CROCHETOUV = 38;
  public static final int CROCHETFERM = 39;
  public static final int ASSOCIER = 25;
  public static final int t_DECLA_INT_FER = 7;
  public static final int VIRGULE = 33;
  public static final int t_texte = 29;
  public static final int t_SCE_FER = 11;
  public static final int t_DECLA_APP_FER = 5;
  public static final int t_DECLA_COM_OUV = 12;
  public static final int t_DECLA_SCE_OUV = 8;
  public static final int t_action = 26;
  public static final int PAROUV = 35;
  public static final int t_BAL_PROG_OUV = 2;
  public static final int PARFERM = 36;
  public static final int EOF = 0;
  public static final int ETAT = 43;
  public static final int FAIT = 22;
  public static final int error = 1;
  public static final int t_sous_Type = 15;
  public static final int FAIRE = 21;
  public static final int POURTOUT = 20;
  public static final int t_Interface = 23;
  public static final int SINON = 18;
  public static final int ALORS = 17;
  public static final int t_DECLA_COM_FER = 13;
  public static final int t_DECLA_SCE_FER = 9;
  public static final int t_executer_scenario = 45;
  public static final int DEUXPOINTS = 42;
  public static final int PGQ = 40;
  public static final int t_BAL_PROG_FER = 3;
  public static final int t_Type = 14;
  public static final int POINT = 32;
  public static final int PROGRAMMER = 24;
  public static final int t_date = 30;
  public static final int POINTVIRGULE = 34;
  public static final int t_ident = 31;
  public static final int DEFINIR = 44;
  public static final int t_autre_appareil = 46;
  public static final int t_DECLA_INT_OUV = 6;
  public static final int t_SCE_OUV = 10;
}

