
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 09 23:04:03 CET 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACOLFERM = 3;
  public static final int TITRE = 4;
  public static final int EOF = 0;
  public static final int AUTEURS = 5;
  public static final int CRITIQUE = 7;
  public static final int TYPE = 6;
  public static final int error = 1;
  public static final int ACOLOUV = 2;
  public static final int CHAINE = 8;
}

